Repository ITP-ICN-G05/ICN-Mobile, pull requests merged in 2025-09, with the labels that each got.

#3 Hotfix/issue 2 development environment setup
  .gitignore
  ICNNavigatorMobile/.gitignore
  Makefile
  README.md
  setup.sh
Labels: docker, hotfix, development-environment

#4 feat: add map screen with placeholder view
  .DS_Store
  ICNNavigatorMobile/App.tsx
  ICNNavigatorMobile/app.json
  ICNNavigatorMobile/package-lock.json
  ICNNavigatorMobile/package.json
  ICNNavigatorMobile/src/components/common/SearchBar.tsx
  ICNNavigatorMobile/src/constants/colors.ts
  ICNNavigatorMobile/src/data/mockCompanies.ts
  ICNNavigatorMobile/src/screens/main/MapScreen.tsx
  ICNNavigatorMobile/src/types/index.ts
  package-lock.json
  package.json
Labels: enhancement

#8 Implementation: Implement the welcome page and the transition effect for page switching.
  ICNNavigatorMobile/App.tsx
  ICNNavigatorMobile/assets/ICN Logo Source/ICN-logo-full.png
  ICNNavigatorMobile/assets/ICN Logo Source/ICN-logo-little.png
  ICNNavigatorMobile/assets/ICN Logo Source/ICN_Masterbrand_Primary_FullCol_CMYK.eps
  ICNNavigatorMobile/assets/ICN Logo Source/ICN_Masterbrand_Primary_Inverse_CMYK.eps
  ICNNavigatorMobile/assets/ICN Logo Source/ICN_Victoria_FullCol_Horizontal CMYK_Nov2022.eps
  ICNNavigatorMobile/assets/ICN Logo Source/ICN_Victoria_Inverse_Horizontal CMYK_Nov2022.eps
  ICNNavigatorMobile/src/effects/pageTransitions.ts
  ICNNavigatorMobile/src/screens/welcome/WelcomeScreen.tsx
Labels: enhancement

#10 fix(map-search): show filter count bar only for filters, not searches
  .DS_Store
  ICNNavigatorMobile/src/components/common/CompanyCard.tsx
  ICNNavigatorMobile/src/components/common/FilterDropdown.tsx
  ICNNavigatorMobile/src/components/common/FilterModal.tsx
  ICNNavigatorMobile/src/components/common/SearchBarWithDropdown.tsx
  ICNNavigatorMobile/src/screens/main/CompaniesScreen.tsx
  ICNNavigatorMobile/src/screens/main/MapScreen.tsx
  Makefile
Labels: bug-fix

#12 hotfix(map): remove duplicate variable declarations in MapScreen
  ICNNavigatorMobile/src/screens/main/MapScreen.tsx
Labels: bug, hotfix, bug-fix

#14 feat(company-detail): implement company detail screen with navigation from companies and map
  ICNNavigatorMobile/App.tsx
  ICNNavigatorMobile/src/navigation/AppNavigator.tsx
  ICNNavigatorMobile/src/screens/main/CompaniesScreen.tsx
  ICNNavigatorMobile/src/screens/main/CompanyDetailScreen.tsx
  ICNNavigatorMobile/src/screens/main/MapScreen.tsx
Labels: enhancement, company

#15 Implementation: Feature/login signup resetps screen
  ICNNavigatorMobile/App.tsx
  ICNNavigatorMobile/assets/ICN Logo Source/ICN-logo-full2.png
  ICNNavigatorMobile/src/components/common/AuthContainer.tsx
  ICNNavigatorMobile/src/components/common/ResetPasswordForm.tsx
  ICNNavigatorMobile/src/components/common/SignInForm.tsx
  ICNNavigatorMobile/src/components/common/SignUpForm.tsx
  ICNNavigatorMobile/src/screens/main/LoginSignUpResetScreen.tsx
  ICNNavigatorMobile/src/screens/welcome/WelcomeScreen.tsx
Labels: enhancement

#17 feat: implement comprehensive Profile screen with user settings
  ICNNavigatorMobile/App.tsx
  ICNNavigatorMobile/src/screens/main/ProfileScreen.tsx
Labels: enhancement

#19 Refactor/ui desgin to figma
  App.js
  ICNNavigatorMobile/App.tsx
  ICNNavigatorMobile/src/components/common/SearchBarWithDropdown.tsx
  ICNNavigatorMobile/src/navigation/BottomTabNavigator.tsx
  ICNNavigatorMobile/src/navigation/CompaniesStack.tsx
  ICNNavigatorMobile/src/navigation/MapStack.tsx
  ICNNavigatorMobile/src/screens/main/MapScreen.tsx
Labels: enhancement, UI design

#28 Feature/nav improvements
  ICNNavigatorMobile/App.tsx
  ICNNavigatorMobile/src/components/common/AuthContainer.tsx
  ICNNavigatorMobile/src/components/common/SignInForm.tsx
  ICNNavigatorMobile/src/components/common/SignUpForm.tsx
  ICNNavigatorMobile/src/contexts/ProfileContext.tsx
  ICNNavigatorMobile/src/contexts/SettingsContext.tsx
  ICNNavigatorMobile/src/contexts/UserContext.tsx
  ICNNavigatorMobile/src/contexts/UserTierContext.tsx
  ICNNavigatorMobile/src/navigation/AppNavigator.tsx
  ICNNavigatorMobile/src/navigation/AuthNavigator.tsx
  ICNNavigatorMobile/src/navigation/BottomTabNavigator.tsx
  ICNNavigatorMobile/src/navigation/CompaniesStack.tsx
  ICNNavigatorMobile/src/navigation/MainNavigator.tsx
  ICNNavigatorMobile/src/navigation/MapStack.tsx
  ICNNavigatorMobile/src/navigation/ProfileNavigator.tsx
  ICNNavigatorMobile/src/navigation/ProfileStack.tsx
  ICNNavigatorMobile/src/navigation/types.ts
  ICNNavigatorMobile/src/screens/main/LoginSignUpResetScreen.tsx
  ICNNavigatorMobile/src/screens/main/ProfileScreen.tsx
  ICNNavigatorMobile/src/screens/main/WelcomeScreen.tsx
  ICNNavigatorMobile/src/store/activitySlice.ts
  ICNNavigatorMobile/src/store/authActions.ts
  ICNNavigatorMobile/src/store/authSlice.ts
  ICNNavigatorMobile/src/store/companiesSlice.ts
  ICNNavigatorMobile/src/store/hooks.ts
  ICNNavigatorMobile/src/store/index.ts
  ICNNavigatorMobile/src/store/notificationsSlice.ts
  ICNNavigatorMobile/src/store/portfolioSlice.ts
  ICNNavigatorMobile/src/store/searchSlice.ts
  ICNNavigatorMobile/src/store/subscriptionSlice.ts
  ICNNavigatorMobile/src/store/userSlice.ts
Labels: enhancement

#30 fix: Map Screen No-zoom-out Fix
  ICNNavigatorMobile/src/screens/main/MapScreen.tsx
Labels: enhancement, hotfix, bug-fix
